import streamlit as st
import numpy as np
import random

# Fake quantum fortune teller
st.title("Quantum Me – Your Future, Decoded by Physics™")
st.write("Enter the last three digits of your phone number. We'll let qubits decide your destiny.")

phone = st.text_input("Last 3 digits?", "777")

if st.button("Ask the Quantum Oracle"):
    # Turn phone input into a seed
    seed = int(phone) if phone.isdigit() else 0
    np.random.seed(seed)
    outcome = random.choice(['00', '01', '10', '11'])

    # List of fake fortunes
    fates = [
        "You'll find $20 on the street. Then lose it to laundry.",
        "A tall stranger will text you. Delete it. It's spam.",
        "You're 78% likely to suarvive Monday. Just Tuesday's iffy.",
        "Quantum says: your butt is basically a black hole. Love yourself.",
        "Big win incoming. Could be lotto. Could be diarrhea. 50/50.",
        "Tonight, you'll jerk off to something weird. Don't worry—we're all guilty.",
        "Your soulmate is already dead. But hey, reincarnation's loading...",
        "The future? You're gonna die. Eventually. Thanks for playing!"
    ]
    fate = random.choice(fates)

    st.balloons()
    st.success(f"🧠 **{outcome}**: {fate}")
    st.image(
        "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Qubit_Sphere.svg/800px-Qubit_Sphere.svg.png",
        caption="Generated by real quantum fuckery."
    )

    # Optional monetization nudge
    if st.checkbox("Donate $5 via Venmo? (optional)"):
        st.info("@quantumme – because entropy's free, therapy isn't.")
